# Generated by Django 5.2.8 on 2025-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(max_length=35)),
                ('cedula', models.IntegerField()),
                ('area', models.CharField(choices=[('Administración', 'Administración'), ('Portería', 'Portería'), ('Celadores', 'Celadores'), ('Bloque madre', 'Bloque madre'), ('Bancos', 'Bancos'), ('Presiembra', 'Presiembra'), ('Siembra', 'Siembra'), ('Riego', 'Riego'), ('Fitosanidad', 'Fitosanidad'), ('Corte', 'Corte'), ('Corte girasol y statice', 'Corte girasol y statice'), ('Armada de girasol y statice', 'Armada de girasol y statice'), ('Sala', 'Sala'), ('Mercados especiales', 'Mercados especiales'), ('Bouquet', 'Bouquet'), ('Boton y descabece', 'Boton y descabece'), ('Monitores', 'Monitores'), ('Desmalece', 'Desmalece'), ('Mallas', 'Mallas'), ('Polietileno', 'Polietileno'), ('Embarazadas', 'Embarazadas'), ('Incapacidades largas', 'Incapacidades largas'), ('Licencia maternidad', 'Licencia maternidad'), ('Aprendices Sena', 'Aprendices Sena'), ('Mantenimiento', 'Mantenimiento'), ('Portería', 'Portería'), ('Aseo', 'Aseo')], default='Bouquet', max_length=30)),
                ('cargo', models.CharField(choices=[('Operario agrícola', 'Operario agrícola'), ('Administración', 'Administración'), ('Celadores', 'Celadores')], default='', max_length=18)),
                ('tipo_contrato', models.CharField(choices=[('Fijo', 'Fijo'), ('Término indefinido', 'Término indefinido'), ('Obra o lavor', 'Obra o lavor'), ('Tiempo parcial', 'Tiempo parcial'), ('Prestación de servicios', 'Prestación de servicios')], default='Fijo', max_length=25)),
                ('vigencia_contrato', models.DateField()),
                ('contacto_emergencia', models.JSONField()),
                ('num_cuenta_banco', models.BigIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('antiguedad_en_empresa', models.CharField(max_length=25)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=60)),
                ('fondo_pension', models.CharField(max_length=90)),
                ('caja_compensacion', models.CharField(max_length=90)),
                ('direccion_vivienda', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=30)),
                ('estrato', models.IntegerField()),
                ('telefono', models.CharField(max_length=16)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('cant_hijos', models.PositiveIntegerField(default=0)),
                ('estado_civil', models.CharField(max_length=15)),
                ('escolaridad', models.CharField(max_length=20)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('inicio_lectiva', models.DateField(blank=True, null=True)),
                ('fin_lectiva', models.DateField(blank=True, null=True)),
                ('inicio_practica', models.DateField(blank=True, null=True)),
                ('fin_practica', models.DateField(blank=True, null=True)),
                ('institucion', models.CharField(max_length=30)),
                ('responsable_aprendiz', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
