# Generated by Django 5.2.8 on 2025-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='institucion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='responsable_aprendiz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
