# Generated by Django 5.2.8 on 2025-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
